## This configuration was generated by terraform-provider-oci

resource oci_core_nat_gateway export_NAT-gateway-demoDarkVCN {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:16.682Z"
  }
  display_name = "NAT gateway-demoDarkVCN"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  #public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaaiq2vtlpq52t3y4pxrprgxjhzx47soj4wyjzokiiogrq5mgeludxa"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_demoDarkVCN.id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:15.510Z"
  }
  display_name     = "Default DHCP Options for demoDarkVCN"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  #manage_default_resource_id = "ocid1.dhcpoptions.oc1.iad.aaaaaaaask5a2vjpwtin3czmgpsdz2voud6225izuri4fytuddar5eeqcmpq"
  manage_default_resource_id = oci_core_vcn.export_demoDarkVCN.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "demodarkvcn.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_internet_gateway export_Internet-gateway-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:16.492Z"
  }
  display_name = "Internet gateway-demoDarkVCN"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_demoDarkVCN.id
}

resource oci_core_subnet export_private-subnet-demoDarkVCN {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:16.485Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-demoDarkVCN.id
  display_name    = "private subnet-demoDarkVCN"
  dns_label       = "sub08251409361"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_route-table-for-private-subnet-demoDarkVCN.id
  security_list_ids = [
    oci_core_security_list.export_security-list-for-private-subnet-demoDarkVCN.id,
  ]
  vcn_id = oci_core_vcn.export_demoDarkVCN.id
}

resource oci_core_vcn export_demoDarkVCN {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:15.510Z"
  }
  display_name = "demoDarkVCN"
  dns_label    = "demodarkvcn"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_security_list export_security-list-for-private-subnet-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:16.949Z"
  }
  display_name = "security list for private subnet-demoDarkVCN"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_demoDarkVCN.id
}

resource oci_core_default_security_list export_Default-Security-List-for-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:15.510Z"
  }
  display_name = "Default Security List for demoDarkVCN"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_demoDarkVCN.default_security_list_id
}

resource oci_core_route_table export_route-table-for-private-subnet-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:16.732Z"
  }
  display_name = "route table for private subnet-demoDarkVCN"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-gateway-demoDarkVCN.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-gateway-demoDarkVCN.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_demoDarkVCN.id
}

resource oci_core_default_route_table export_default-route-table-for-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:15.510Z"
  }
  display_name = "default route table for demoDarkVCN"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  manage_default_resource_id = oci_core_vcn.export_demoDarkVCN.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-gateway-demoDarkVCN.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_service_gateway export_Service-gateway-demoDarkVCN {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/rcarrasco@spsolutions.com.mx"
    "Oracle-Tags.CreatedOn" = "2024-08-25T14:09:16.498Z"
  }
  display_name = "Service gateway-demoDarkVCN"
  freeform_tags = {
    "VCN" = "VCN-2024-08-25T14:08:56"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_demoDarkVCN.id
}

